name: Release

on:
  release:
    types: [released]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: uv pip install -e . --group release
    - name: Install Build Tool
      run: uv pip install build
    - name: Build
      run: python -m build
    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/* --verbose
